# Generated by Django 4.2.6 on 2023-10-23 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_cover_image_alter_category_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='cover_image',
            new_name='coverImage',
        ),
    ]
