# Generated by Django 4.2.5 on 2023-10-18 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='Id',
        ),
        migrations.AlterField(
            model_name='department',
            name='Code',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
