# Generated by Django 4.2.6 on 2023-12-29 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routine',
            name='RoomNo',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
