# Generated by Django 4.2.5 on 2023-10-19 09:01

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='Room',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='StudentId',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=12, null=True), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='ClassroomId',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='student',
            name='ClassroomId',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), default=list, size=None),
        ),
    ]
