# Generated by Django 4.2.6 on 2023-12-30 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_routine_roomno'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroomcontent',
            name='Head',
            field=models.IntegerField(default=None),
        ),
    ]
