# Generated by Django 4.2.5 on 2023-10-18 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_department_id_alter_department_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='Id',
        ),
        migrations.AddField(
            model_name='school',
            name='Code',
            field=models.CharField(default=None, max_length=10, primary_key=True, serialize=False),
        ),
    ]
