# Generated by Django 4.2.6 on 2023-12-30 16:33

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_classroomcontent_head'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecontent',
            name='CoverImage',
            field=models.ImageField(default=None, upload_to=''),
        ),
        migrations.AddField(
            model_name='coursecontent',
            name='Enrolled',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='faculty',
            name='CourseId',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), default=list, size=None),
        ),
        migrations.AddField(
            model_name='student',
            name='CourseId',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), default=list, size=None),
        ),
    ]
