# Generated by Django 4.2.6 on 2023-12-30 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_coursecontent_coverimage_coursecontent_enrolled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecontent',
            name='VerifiedBy',
            field=models.CharField(default=None, max_length=12),
        ),
        migrations.AddField(
            model_name='coursecontent',
            name='VerifierName',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
