# Generated by Django 4.2.5 on 2023-10-31 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='country',
        ),
    ]
