# Generated by Django 4.2.6 on 2023-12-30 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_coursecontent_verifiedby_coursecontent_verifiername'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecontent',
            name='Enrolled',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='coursecontent',
            name='Like',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
