# Generated by Django 4.2.6 on 2023-12-30 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_coursecontent_coursecode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecontent',
            name='CourseBy',
            field=models.CharField(max_length=50),
        ),
    ]
