# Generated by Django 4.2.6 on 2023-12-30 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_coursecontent_courseby'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecontent',
            name='Instructor',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='coursecontent',
            name='CourseBy',
            field=models.CharField(max_length=12),
        ),
    ]
