# Generated by Django 4.2.5 on 2023-12-31 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_coursecontent_instructor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroomcontent',
            name='description',
            field=models.TextField(default=None, null=True),
        ),
    ]
