# Generated by Django 4.2.5 on 2023-12-31 09:27

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_classroomcontent_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classroomcontent',
            old_name='description',
            new_name='Description',
        ),
        migrations.AddField(
            model_name='classroomcontent',
            name='IsHead',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='classroomcontent',
            name='UploadedFiles',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='classroomcontent',
            name='ObjectKey',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), default=list, size=None),
        ),
    ]
