# Generated by Django 4.2.5 on 2023-12-31 13:36

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_rename_description_classroomcontent_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroomcontent',
            name='ObjectKey',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='classroomcontent',
            name='UploadedFiles',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), default=list, size=None),
        ),
    ]
