# Generated by Django 4.2.5 on 2023-12-31 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_classroomcontent_objectkey_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroomcontent',
            name='IsHead',
            field=models.BooleanField(default=None),
        ),
    ]
