# Generated by Django 4.2.5 on 2024-01-03 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_classroomcontent_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroomcompressedfile',
            name='file_name',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
