# Generated by Django 4.2.6 on 2024-01-02 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_routine_endtime_alter_routine_starttime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routine',
            name='Hour',
        ),
    ]
