# Generated by Django 4.2.5 on 2024-01-03 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_classroomcompressedfile_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroomcompressedfile',
            name='file_name',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
