# Generated by Django 4.2.6 on 2024-01-02 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_remove_routine_hour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routine',
            name='BlockNo',
        ),
    ]
