# Generated by Django 4.2.5 on 2024-01-03 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_classroomcompressedfile_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroomcompressedfile',
            name='file_name',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
    ]
