# Generated by Django 4.2.5 on 2024-01-03 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_classroomcompressedfile_file_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroomcontent',
            name='ObjectKey',
        ),
        migrations.AddField(
            model_name='classroomcontent',
            name='Object_Key',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
